- name: Remove alacritty
  ansible.builtin.file:
    path: '{{ home }}/alacritty/'
    state: absent
  tags:
    - alacritty

- name: Clone alacritty from github
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty.git'
    accept_hostkey: true
    dest: '{{ home }}/alacritty/'
  tags:
    - alacritty

- name: Check if cargo is installed
  ansible.builtin.command: command -v cargo
  register: cargo_exists
  ignore_errors: true
  tags:
    - cargo
    - alacritty

- name: Download installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - cargo
    - alacritty

- name: Install rust/cargo
  when: cargo_exists is failed
  ansible.builtin.command: /tmp/sh.rustup.rs -y
  tags:
    - cargo
    - alacritty

- name: Make env update file executable
  when: cargo_exists is failed
  ansible.builtin.file:
    path: '{{ home }}/.cargo/env'
    owner: '{{ user }}'
    mode: '0775'
  tags:
    - cargo
    - alacritty

- name: Install rust compiler with rustup
  when: cargo_exists is failed
  ansible.builtin.command: '{{ home }}/.cargo/env && rustup override set stable && rustup update stable'
  args:
    chdir: '{{ home }}/alacritty/'
  tags:
    - cargo
    - alacritty

- name: Build the super duper fast terminal
  ansible.builtin.command: cargo build --release --no-default-features --features=x11
  args:
    chdir: '{{ home }}/alacritty/'
  tags:
    - alacritty

# If all goes well, this should place a binary at target/release/alacritty.

# Post installation
#
# if `infocmp alacritty` returns without errors,
# terminfo is installed. Otherwise install it with
# sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
- name: Install terminfo
  become: true
  ansible.builtin.command: tic -xe alacritty,alacritty-direct '{{ home }}/alacritty/extra/alacritty.info'
  tags:
    - alacritty

# Man Page
#
# sudo mkdir -p /usr/local/share/man/man1 # gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null
# gzip -c extra/alacritty-msg.man | sudo tee /usr/local/share/man/man1/alacritty-msg.1.gz > /dev/null
#
# ZSH Completions
#
# To install the completions for zsh, you can place the extra/completions/_alacritty file in any directory referenced by $fpath.
#
# If you do not already have such a directory registered through your ~/.zshrc, you can add one like this:
#
# mkdir -p ${ZDOTDIR:-~}/.zsh_functions
# echo 'fpath+=${ZDOTDIR:-~}/.zsh_functions' >> ${ZDOTDIR:-~}/.zshrc
# Then copy the completion file to this directory:
#
# cp extra/completions/_alacritty ${ZDOTDIR:-~}/.zsh_functions/_alacritty
