- name: Dotfiles exists
  ansible.builtin.stat:
    path: '{{ home }}/.dotfiles'
  register: dotfiles
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/adelgado0723/.dotfiles_mac.git'
    bare: false
    dest: '{{ home }}/.dotfiles'
  tags:
    - install
    - dotfiles
    - stow
  when: not dotfiles.stat.exists

- name: Stow dotfiles
  ansible.builtin.command: stow -R .
  args:
    chdir: '{{ home }}/.dotfiles/'
  tags:
    - install
    - dotfiles
    - stow
