# LSP Setup - https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
#
# treesitter
- name: Treesitter
  ansible.builtin.npm:
    name: tree-sitter-cli
    global: true
  tags:
    - install
    - lsp

# LSP Setup - Lua packages are now installed via Brewfile (tasks/brew-bundle.yml)
# "Lua" - lua-language-server, luajit, and luarocks are in Brewfile

# https://github.com/hrsh7th/vscode-langservers-extracted
- name: Install vscode langservers (jsonls, html,  eslint  server)
  ansible.builtin.npm:
    name: vscode-langservers-extracted
    global: true
  tags:
    - install
    - lsp

# "pyright"
- name: Install pyright server
  ansible.builtin.pip:
    name: pyright
  tags:
    - install
    - lsp

# "gopls"
# - name: Install gopls
#   ansible.builtin.command: '{{ go_bin_path }}/go install golang.org/x/tools/gopls@latest'
#   tags:
#     - install
#     - lsp
#
# "golangci_lint_ls"
- name: Install golangci_lint_ls
  ansible.builtin.command: '{{ go_bin_path }}/go install github.com/nametake/golangci-lint-langserver@latest'
  tags:
    - install
    - lsp

- name: Install golangci_lint
  ansible.builtin.shell: 'curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v{{ golangci_lint_version }}'
  tags:
    - install
    - lsp

# "clangd" # installed in core setup
# "dockerls"
- name: Install dockerls
  ansible.builtin.npm:
    name: dockerfile-language-server-nodejs
    global: true
  tags:
    - install
    - lsp

# "svelte"
- name: Install svelte server
  ansible.builtin.npm:
    name: svelte-language-server
    global: true
  tags:
    - install
    - lsp

# "tsserver"
- name: Install Typescript server
  ansible.builtin.npm:
    name: typescript-language-server
    global: true
  tags:
    - install
    - lsp

# "bashls"
- name: Install bashls
  ansible.builtin.npm:
    name: bash-language-server
    global: true
  tags:
    - install
    - lsp

# "sqlls"
- name: Install sqlls
  ansible.builtin.npm:
    name: sql-language-server
    global: true
  tags:
    - install
    - lsp

# "yamlls"
- name: Install yamlls
  ansible.builtin.command: yarn global add yaml-language-server
  tags:
    - install
    - lsp

# null_ls
# prettier - formatting
- name: Install prettier formatter
  ansible.builtin.npm:
    name: prettier
    global: true
  tags:
    - install
    - lsp

# black - formatting
- name: Install black python formatter
  ansible.builtin.pip:
    name: black
  tags:
    - install
    - lsp

# ansiblels
- name: Install ansiblels
  ansible.builtin.npm:
    name: ansible-language-server
    global: true
  tags:
    - install
    - lsp

# ansible-lint
- name: Install ansible-lint
  ansible.builtin.pip:
    name: ansible-lint
  tags:
    - install
    - lsp

- name: Install markdownlint-cli
  ansible.builtin.npm:
    name: markdownlint-cli
    global: true
  tags:
    - install
    - lsp

- name: Install prettierd
  ansible.builtin.npm:
    name: '@fsouza/prettierd'
    global: true
  tags:
    - install
    - lsp

- name: Install eslint_d
  ansible.builtin.npm:
    name: eslint_d
    global: true
  tags:
    - install
    - lsp

- name: Install flake8
  ansible.builtin.pip:
    name: flake8
  tags:
    - install
    - lsp

- name: Install spectral (yaml and json)
  ansible.builtin.npm:
    name: '@stoplight/spectral-cli'
    global: true
  tags:
    - install
    - lsp

- name: Install prismals
  ansible.builtin.npm:
    name: '@prisma/language-server'
    global: true
  tags:
    - install
    - lsp

- name: Install emmet-ls
  ansible.builtin.npm:
    name: 'emmet-ls'
    global: true
  tags:
    - install
    - lsp

- name: Install astro ls
  ansible.builtin.npm:
    name: '@astrojs/language-server'
    global: true
  tags:
    - install
    - lsp

- name: Install docker compose ls
  ansible.builtin.npm:
    name: '@microsoft/compose-language-service'
    global: true
  tags:
    - install
    - lsp

- name: Clone kotlin lsp
  ansible.builtin.git:
    repo: 'git@github.com:fwcd/kotlin-language-server.git'
    recursive: true
    dest: '{{ home }}/kotlin-language-server'
  tags:
    - install
    - lsp

- name: Build kotlin lsp
  ansible.builtin.command: ./gradlew :server:installDist
  args:
    chdir: '{{ home }}/kotlin-language-server'
  tags:
    - install
    - lsp

- name: Ensure Mason Kotlin language server directories exist
  file:
    path: '{{ home }}/.local/share/nvim/mason/packages/kotlin-language-server/server/bin'
    state: directory
    mode: '0755'
    recurse: yes

- name: Copy built Kotlin language server files to Mason directory
  copy:
    src: '{{ home }}/kotlin-language-server/server/build/install/server/'
    dest: '{{ home }}/.local/share/nvim/mason/packages/kotlin-language-server/server/'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'
    remote_src: yes

- name: Symlink kotlin-language-server binary to Mason bin
  file:
    src: '{{ home }}/.local/share/nvim/mason/packages/kotlin-language-server/server/bin/kotlin-language-server'
    dest: '{{ home }}/.local/share/nvim/mason/bin/kotlin-language-server'
    state: link
    force: yes
