- name: Remove neovim
  ansible.builtin.file:
    path: '{{ home }}/neovim/'
    state: absent
  tags:
    - wsl
    - install
    - neovim

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: '{{ home }}/.local/share/nvim/site/pack/packer/start/packer.nvim'
  tags:
    - wsl
    - install
    - neovim

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: '{{ home }}/neovim'
  tags:
    - wsl
    - install
    - neovim

- name: Build neovim
  ansible.builtin.command: 'make -j 20'
  args:
    chdir: '{{ home }}/neovim'
  tags:
    - wsl
    - install
    - neovim

- name: Install neovim
  become: true
  ansible.builtin.command: 'make install'
  args:
    chdir: '{{ home }}/neovim'
  tags:
    - wsl
    - install
    - neovim

# luarocks is now installed via Brewfile (tasks/brew-bundle.yml)
