# Tmux Setup - tmux is now installed via Brewfile (tasks/brew-bundle.yml)

- name: create tpm plugins folder if it doesn't exist
  file:
    path: '{{ home }}/.tmux/plugins/'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  tags:
    - install
    - dotfiles
    - tmux

- name: clone tpm
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm.git'
    dest: '{{ home }}/.tmux/plugins/tpm'
  tags:
    - install
    - dotfiles
    - tmux

# - name: source tmux config
#   shell: 'tmux source {{ home }}/.tmux.conf'
#   tags:
#     - install
#     - dotfiles
#     - tmux

- name: install tpm plugins
  shell: '{{ home }}/.tmux/plugins/tpm/bin/install_plugins'
  tags:
    - install
    - dotfiles
    - tmux

