# Zsh Setup - zsh is now installed via Brewfile (tasks/brew-bundle.yml)

- name: change shell to zsh
  become: true
  #  shell: chsh -s $(chsh -l | grep zsh | sort -r | awk '(NR == 1){print $1}')
  shell: chsh -s $(which zsh) {{ user }}
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: check if ~/.oh-my-zsh/ exists
  stat:
    path: '{{ home }}/.oh-my-zsh'
  register: oh_my_stats
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: install oh my zsh
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '{{ home }}/.oh-my-zsh'
    depth: 1
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
  when: oh_my_stats.stat.exists == False

- name: install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git' 
    dest: '{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
